[project]
name = "netapp_mcp_server"
version = "0.1.0"
description = "MCP server with custom AIDP RAG search functionality"
authors = [
    { name = "Shreya Menneni", email = "Shreya.Menneni@netapp.com" }
]
dependencies = [
    "fastmcp",
]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
server = "scripts.scripts:server"
inspector = "scripts.scripts:inspector"