[project]
name = "netapp-data-engine-mcp"
version = "0.1.0"
description = "MCP server with custom AIDP RAG search functionality"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Shreya Menneni", email = "Shreya.Menneni@netapp.com" }
]
dependencies = [
    "fastmcp",
]
license = { file="LICENSE" }

[build-system]
requires = [
    "setuptools>=61.0.0", 
    "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["netapp_rag_server"]

[project.scripts]
server = "netapp_rag_server.main:main"